project:
  type: book
book:
  title: Statistics Notes
  author: Ralf Becker
  date: 25/01/2026
  chapters:
  - index.qmd
  - intro.qmd
  - datatypes.qmd
  - summary.qmd
  - references.qmd
bibliography: references.bib
format:
  html:
    theme:
    - cosmo
    - brand
    css: include/webex.css
    include-after-body:
    - include/webex-after-body.html
